version: "3"

services:

  server_app:
    build:
      context: ./server_app
      dockerfile: Dockerfile
      args:
          SERVER_FILE: html
    container_name: server_app
    restart: always
    environment:
      - APP_NAME=server_app
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9001"
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "127.0.0.1:80:80"
